version: '3.8'
networks:
  networkname:

# Services
services:

  # Nginx Service
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    working_dir: /var/www/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - networkname
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped
    depends_on:
      - wordpress

  # Wordpress Service
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    working_dir: /var/www/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - networkname
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mariadb

  # MariaDB Service
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_NAME=${MARIADB_NAME}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PWD=${MARIADB_PWD}
        - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
    image: mariadb
    container_name: mariadb
    networks:
      - networkname
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped

# Volumes
volumes:

  # Wordpress
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mmeising/data/wp_data"

  # MariaDB
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/mmeising/data/db_data"
